### ISSUE TITLE
Various golfing languages

### ISSUE THREAD

**Issue by nloveladyallen** [zenware/FizzBuzz#56]
There are a ton of interesting golf FizzBuzzes [here](http://codegolf.stackexchange.com/questions/58615/1-2-fizz-4-buzz/58664).

**Comment by zenware** [comment]
I'm very interested in Hexagony and Labyrinth because of their visual, movement/path-traversal based nature. It's something I've never seen before, also they had the best examples. At least to the end I use this project it's not really for golfing languages, but rather to quickly infer a lot of information about the syntax of a given language so I can start writing code in it immediately.

Though for well-defined examples of a golf-language that walk the reader through everything that is happening, probably through the use of code comments rather than commit messages I don't see a reason not to accept stuff like that. Since it's all about studying the syntactical representation of programs. (In a rather unrigorous way)
